---
language: python

services:
  - docker

jobs:
  include:
    - stage: Test Docker image
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t python-pipenv -f Dockerfile .
        - docker images
      script:
        - docker run --rm python-pipenv pipenv install django
        - docker run --rm python-pipenv pipenv install mysqlclient
        - docker run --rm python-pipenv pipenv install psycopg2
        - docker run --rm python-pipenv pipenv install pillow
    - stage: Deploy to Docker HUB
      if: branch =~ /^(master|release\/.*)$/
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t python-pipenv -f Dockerfile .
        - docker tag python-pipenv $DOCKER_USERNAME/python-pipenv:$(cat VERSION)
        - docker tag python-pipenv $DOCKER_USERNAME/python-pipenv:latest
      script:
        - docker push $DOCKER_USERNAME/python-pipenv:$(cat VERSION)
        - docker push $DOCKER_USERNAME/python-pipenv:latest
