---
language: python

services:
  - docker

jobs:
  include:
    - stage: Build Docker Image - Python 3.7
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t python-pipenv -f Dockerfile .
        - docker images
      script:
        - docker run --rm python-pipenv pipenv install django
